function [fitresult, gof] = createFit(tToFit, yToFit)
%CREATEFIT(TTOFIT,YTOFIT)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : tToFit
%      Y Output: yToFit
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 03-Jan-2020 12:06:10


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( tToFit, yToFit );

% Set up fittype and options.
ft = fittype( 'exp2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [-.123 .1363 .3 -.9];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'yToFit vs. tToFit', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'tToFit', 'Interpreter', 'none' );
ylabel( 'yToFit', 'Interpreter', 'none' );
grid on


