# -*- coding: utf-8 -*-
'''
load and plot data generated by normPlots.m MATLAB file using plotly

'''
import numpy as np
from scipy.io import loadmat
import plotly.graph_objects as go
import plotly.io as pio
from plotly.subplots import make_subplots
import plotly.express as px

plot_mat = loadmat(r'..\normPlots.mat')

nAPs = plot_mat['nAPs'][0]

all_norm_plots = plot_mat['normPlots_struct'][0]

